name: ❓ Question
description: Ask a question about the Minecraft Server Monitor Bot
title: '[Question]: '
labels: ['question', 'needs-response']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Please fill out the form below to help us provide the best answer.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following steps
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have read the documentation and README
          required: true
        - label: I have checked the troubleshooting section
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What category does your question fall into?
      options:
        - Setup and Installation
        - Configuration
        - Bot Usage
        - Server Compatibility
        - Discord Integration
        - Troubleshooting
        - Feature Usage
        - Development
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please describe your question in detail
      placeholder: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your setup or situation
      placeholder: |
        - What are you trying to achieve?
        - What have you already tried?
        - Any relevant configuration details?

  - type: textarea
    id: environment
    attributes:
      label: Environment Details (if relevant)
      description: Share environment details if they're relevant to your question
      placeholder: |
        - Operating System:
        - Node.js Version:
        - Bot Version:
        - Minecraft Server Type:

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any additional information that might be helpful
      placeholder: Screenshots, logs, or other relevant details... 